language: cpp
version: ~> 1.0

#Using trick from https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
# https://github.com/travis-ci/travis-ci/issues/6300
# https://github.com/travis-ci/travis-ci/issues/7100

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xerces-c; fi
  - git clone git@github.com:ucb-cyarp/amduprof.git depends/amduprof
  - export START_PATH=`pwd`

before_script:
    - if [[ "$COMPILER" = "g++-7"        ]] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export CXX="g++-7" CC="gcc-7";              fi
    - if [[ "$COMPILER" = "clang++-6.0"  ]] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export CXX="clang++-6.0" CC="clang-6.0";    fi
    - export PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/bin:$PATH"
    - export LD_LIBRARY_PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/lib:$LD_LIBRARY_PATH"
    - export LD_LIBRARY_PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/bin:$LD_LIBRARY_PATH"
    - export LIBRARY_PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/lib:$LIBRARY_PATH"
    - export LIBRARY_PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/bin:$LIBRARY_PATH"
    - export C_INCLUDE_PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/include:$C_INCLUDE_PATH"
    - export CPLUS_INCLUDE_PATH="$START_PATH/depends/amduprof/AMDuProf_Linux_x64_3.1.35/include:$CPLUS_INCLUDE_PATH"

matrix:
  include:
    - compiler: gcc
      os: linux
      dist: bionic
      env: COMPILER=g++-7
    - compiler: clang
      os: linux
      dist: bionic
      env: COMPILER=clang++-6.0
    - compiler: clang
      os: osx
      osx_image: xcode11.2
      env: COMPILER=clang++
  exclide:
    - compiler: gcc
    - compiler: clang

addons:
  apt:
    packages:
    - clang-6.0
    - gcc-7
    - g++-7

script:
  - echo $CXX; echo $CC
  - cd travis
  - ./travis_build.sh

notifications:
  slack:
    secure: h5AYGVV90kulQHihxIrR1Adf78PXL7V+UIDdn8Ts/vpmV972bONud9XXkTZGVz/Dv6GqmLYXHRVaaFfex3dB5kJwn4rWtpR3nyAFF606ZRgIIucph+vd/xWCexf8vwYzmEQ5zZ3J0Ixw/LLVB+Yk/wShcIlupr4escnfmfMEPkynR90Dgs18mMWGa1iep4eeayFrGrj4FHIloGyifoYHBqpAyCJgsfw5IuUVfDXuFBOH67AUCLmn7hqp+7xDHEz4CkX8EduM6HndG5TLDOZgxHqoGQ67nU86pyB9pg7TgxfbZlVJ7Sc9W8eC//Gv0b0BspLQefe0rTCSl2FEuz7Y6160tAzL4s3EabFxDcU3IC0T9U4WVvSfLsv94EftsUnhgvTu/ggr2uzACT5FsyabRfgt0ZHZvg5ypeBwkOzKOCgVFLo1HqBRze/4GfAs1e9RsEp+lxjkwWbl5+rwvcLbs1aiM9PJ/pBJq3lQhmAq3wvyLkvyOT5r+Y17hHqvl3p+PrkGvYaHs5jLrykN1hCYqY96KOLELHMyj/ugSWQoPmUUUS8zhOY8byOBORcykGe/0ErZWAeVXrLaJ+IGKvQUw74HQSnicSGmTdVHFqZhHYAaGVsViRrSP7xncDAG1G16nw3XGNqs+5IJQw6L9gBRlSUKU7o4lp0uBq2PgpbEf9M=
