function [ArrayLengthBlocks, BlockSizeint32_tElements, BalancingNOPs, InitialNOPs, SteadyClockWalltimems, ExpectedBlockIDCore_Client, StartBlockIDCore_Client, EndBlockIDCore_Client, ErroredCore_Client, TransactionCore_Client] = import_open_loop_raw_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [ARRAYLENGTHBLOCKS, BLOCKSIZEINT32_TELEMENTS, BALANCINGNOPS,
%  INITIALNOPS, STEADYCLOCKWALLTIMEMS, EXPECTEDBLOCKIDCORE_Client,
%  STARTBLOCKIDCORE_Client, ENDBLOCKIDCORE_Client, ERROREDCORE_Client, TRANSACTIONCORE_Client] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [ARRAYLENGTHBLOCKS, BLOCKSIZEINT32_TELEMENTS, BALANCINGNOPS,
%  INITIALNOPS, STEADYCLOCKWALLTIMEMS, EXPECTEDBLOCKIDCORE_Client,
%  STARTBLOCKIDCORE_Client, ENDBLOCKIDCORE_Client, ERROREDCORE_Client, TRANSACTIONCORE_Client] =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [ArrayLengthBlocks, BlockSizeint32_tElements, BalancingNOPs, InitialNOPs, SteadyClockWalltimems, ExpectedBlockIDCore_Client, StartBlockIDCore_Client, EndBlockIDCore_Client, ErroredCore_Client, TransactionCore_Client] = importfile("/Users/cyarp/git/benchmarking-github/core-core/results/bwrc-sr-amd-32c/open_loop/results_open_loop_single_point_tracker/report_open_loop_raw.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Jan-2020 10:_Client7:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ArrayLengthBlocks", "BlockSizeint32_tElements", "BalancingNOPs", "InitialNOPs", "SteadyClockWalltimems", "Var6", "Var7", "ExpectedBlockIDCore_Client", "StartBlockIDCore_Client", "EndBlockIDCore_Client", "ErroredCore_Client", "Var12", "TransactionCore_Client", "Var1_Server", "Var1_Client", "Var16", "Var17", "Var18", "Var19"];
opts.SelectedVariableNames = ["ArrayLengthBlocks", "BlockSizeint32_tElements", "BalancingNOPs", "InitialNOPs", "SteadyClockWalltimems", "ExpectedBlockIDCore_Client", "StartBlockIDCore_Client", "EndBlockIDCore_Client", "ErroredCore_Client", "TransactionCore_Client"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "categorical", "string", "double", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var6", "Var7", "Var12", "Var1_Server", "Var1_Client", "Var16", "Var17", "Var18", "Var19"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var6", "Var7", "ErroredCore_Client", "Var12", "Var1_Server", "Var1_Client", "Var16", "Var17", "Var18", "Var19"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
ArrayLengthBlocks = tbl.ArrayLengthBlocks;
BlockSizeint32_tElements = tbl.BlockSizeint32_tElements;
BalancingNOPs = tbl.BalancingNOPs;
InitialNOPs = tbl.InitialNOPs;
SteadyClockWalltimems = tbl.SteadyClockWalltimems;
ExpectedBlockIDCore_Client = tbl.ExpectedBlockIDCore_Client;
StartBlockIDCore_Client = tbl.StartBlockIDCore_Client;
EndBlockIDCore_Client = tbl.EndBlockIDCore_Client;
ErroredCore_Client = tbl.ErroredCore_Client;
TransactionCore_Client = tbl.TransactionCore_Client;
end