#include "intrin_bench_default_defines.h"

#ifdef __AVX2__
    //==========_mm256_add_epi8==========
    void kernel_only_asm_mm256_add_epi8_unroll120()
    {
        for(int i = 0; i<STIM_LEN/(256*15); i++)
        {
            asm volatile(
                //1
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //2
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //3
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //4
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //5
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //6
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //7
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //8
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //9
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //10
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //11
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //12
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //13
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //14
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                //15
                "vpaddb  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddb  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddb  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddb  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddb  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddb  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddb  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddb  %%ymm14, %%ymm15, %%ymm14\n\t"
                :
                :
                : MMREG(15), MMREG(14), MMREG(13), MMREG(12), MMREG(11), MMREG(10), MMREG(9), MMREG(8), MMREG(7), MMREG(6), MMREG(5), MMREG(4), MMREG(3), MMREG(2), MMREG(1), MMREG(0)
            );
        }
    }

    //==========_mm256_add_epi16==========
    void kernel_only_asm_mm256_add_epi16_unroll120()
    {
        for(int i = 0; i<STIM_LEN/(128*15); i++)
        {
            asm volatile(
                //1
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //2
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //3
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //4
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //5
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //6
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //7
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //8
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //9
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //10
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //11
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //12
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //13
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //14
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                //15
                "vpaddw  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddw  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddw  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddw  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddw  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddw  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddw  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddw  %%ymm14, %%ymm15, %%ymm14\n\t"
                :
                :
                : MMREG(15), MMREG(14), MMREG(13), MMREG(12), MMREG(11), MMREG(10), MMREG(9), MMREG(8), MMREG(7), MMREG(6), MMREG(5), MMREG(4), MMREG(3), MMREG(2), MMREG(1), MMREG(0)
            );
        }
    }

    //==========_mm256_add_epi32==========
    void kernel_only_asm_mm256_add_epi32_unroll120()
    { 
        for(int i = 0; i<STIM_LEN/(64*15); i++)
        {
            asm volatile(
                //1
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //2
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //3
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //4
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //5
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //6
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //7
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //8
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //9
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //10
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //11
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //12
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //13
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //14
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //15
                "vpaddd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddd  %%ymm14, %%ymm15, %%ymm14\n\t"
                :
                :
                : MMREG(15), MMREG(14), MMREG(13), MMREG(12), MMREG(11), MMREG(10), MMREG(9), MMREG(8), MMREG(7), MMREG(6), MMREG(5), MMREG(4), MMREG(3), MMREG(2), MMREG(1), MMREG(0)
            );
        }
    }

    //==========_mm256_add_epi64==========
    void kernel_only_asm_mm256_add_epi64_unroll120()
    { 
        for(int i = 0; i<STIM_LEN/(32*15); i++)
        {
            asm volatile(
                //1
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //2
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //3
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //4
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //5
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //6
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //7
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //8
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //9
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //10
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //11
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //12
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //13
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //14
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                //15
                "vpaddq  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vpaddq  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vpaddq  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vpaddq  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vpaddq  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vpaddq  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vpaddq  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vpaddq  %%ymm14, %%ymm15, %%ymm14\n\t"
                :
                :
                : MMREG(15), MMREG(14), MMREG(13), MMREG(12), MMREG(11), MMREG(10), MMREG(9), MMREG(8), MMREG(7), MMREG(6), MMREG(5), MMREG(4), MMREG(3), MMREG(2), MMREG(1), MMREG(0)
            );
        }
    }
#endif

#ifdef __AVX__
    //==========_mm256_add_ps==========
    void kernel_only_asm_mm256_add_ps_unroll120()
    {
        for(int i = 0; i<STIM_LEN/(64*15); i++)
        {
            asm volatile(
                //1
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //2
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //3
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //4
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //5
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //6
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //7
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //8
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //9
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //10
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //11
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //12
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //13
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //14
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                //15
                "vaddps  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddps  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddps  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddps  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddps  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddps  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddps  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddps  %%ymm14, %%ymm15, %%ymm14\n\t"
                :
                :
                : MMREG(15), MMREG(14), MMREG(13), MMREG(12), MMREG(11), MMREG(10), MMREG(9), MMREG(8), MMREG(7), MMREG(6), MMREG(5), MMREG(4), MMREG(3), MMREG(2), MMREG(1), MMREG(0)
            );
        }
    }

    //==========_mm256_add_pd==========
    void kernel_only_asm_mm256_add_pd_unroll120()
    {
        for(int i = 0; i<STIM_LEN/(32*15); i++)
        {
            asm volatile(
                //1
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //2
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //3
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //4
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //5
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //6
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //7
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //8
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //9
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //10
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //11
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //12
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //13
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //14
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                //15
                "vaddpd  %%ymm0, %%ymm1, %%ymm0\n\t"
                "vaddpd  %%ymm2, %%ymm3, %%ymm2\n\t"
                "vaddpd  %%ymm4, %%ymm5, %%ymm4\n\t"
                "vaddpd  %%ymm6, %%ymm7, %%ymm6\n\t"
                "vaddpd  %%ymm8, %%ymm9, %%ymm8\n\t"
                "vaddpd  %%ymm10, %%ymm11, %%ymm10\n\t"
                "vaddpd  %%ymm12, %%ymm13, %%ymm12\n\t"
                "vaddpd  %%ymm14, %%ymm15, %%ymm14\n\t"
                :
                :
                : MMREG(15), MMREG(14), MMREG(13), MMREG(12), MMREG(11), MMREG(10), MMREG(9), MMREG(8), MMREG(7), MMREG(6), MMREG(5), MMREG(4), MMREG(3), MMREG(2), MMREG(1), MMREG(0)
            );
        }
    }
#endif
